CREATE TABLE BUILDINGS(
  building_id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(150),
  onFire VARCHAR(10),
  shape SDO_GEOMETRY
);

CREATE TABLE HYDRANTS(
  hydrants_id VARCHAR(10) PRIMARY KEY,
  shape SDO_GEOMETRY
);

INSERT INTO USER_SDO_GEOM_METADATA VALUES ('XXXBUILDINGS','SHAPE', SDO_DIM_ARRAY(
SDO_DIM_ELEMENT('X', 0, 865, 0.005),
SDO_DIM_ELEMENT('Y', 0, 580, 0.005)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA VALUES ('XXXHYDRANTS','SHAPE', SDO_DIM_ARRAY(
SDO_DIM_ELEMENT('X', 0, 865, 0.005),
SDO_DIM_ELEMENT('Y', 0, 580, 0.005)),NULL);

CREATE INDEX HYDRANT_SPATIAL_INDEX
ON HYDRANTS(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE  INDEX BUILDING_SPATIAL_INDEX
ON BUILDINGS(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

COMMIT;